---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: receiver
spec:
  hosts:
    - receiver
  http:
  - route:
    - destination:
        host: receiver-a
      weight: 50
    - destination:
        host: eceiver-b
      weight: 50